apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democrm-app-of-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://35.178.81.143/piaseckip/gitopsconfig.git
    targetRevision: HEAD
    path: ./apps
  destination:
    server: https://kubernetes.default.svc
    # server: https://34.116.222.43
    namespace: default