apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-ctrl
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://35.178.81.143/piaseckip/gitops.git
    targetRevision: HEAD
    path: ./infra-apps/nginx-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: default