apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://35.178.81.143/piaseckip/gitops.git
    targetRevision: HEAD
    path: ./infra-apps/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    # server: https://34.116.222.43
    namespace: default